- name: Variables from prompt
  hosts: localhost
  vars_prompt: 
    - name: USERNAME
      prompt: Please enter your username
      private: false #user can see what the yare entering
    - name: PASSWORD
      prompt: Please enter passowrd
      private: True #user cannot see what they are entering
  tasks: 
  - name: print and check the values
    ansible.builtin.debug:
      msg: "username is : {{USERNAME}}
            passowrd is : {{PASSWORD}}"
